(part "ESMIT-4180_A"
    (packageRef "ESMIT4180A")
    (interface
        (port "1" (symbPinId 1) (portName "PRI_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PRI_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SEC_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SEC_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "152")
    (property "Mouser_Part_Number" "851-ESMIT-4180/A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Sumida/ESMIT-4180-A?qs=Yx5fhyb%252BnH2J%2FiILZQpWMg%3D%3D")
    (property "Manufacturer_Name" "Sumida")
    (property "Manufacturer_Part_Number" "ESMIT-4180/A")
    (property "Description" "Pulse Transformers")
    (property "Datasheet_Link" "http://products.sumida.com/products/pdf/CBM5D33(ESMIT4180).pdf")
    (property "symbolName1" "ESMIT-4180_A")
)
