(part "7490100111"
    (packageRef "7490100111")
    (interface
        (port "1" (symbPinId 1) (portName "TD+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CTD") (portType INOUT))
        (port "3" (symbPinId 3) (portName "TD-") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "RD+") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CRD") (portType INOUT))
        (port "8" (symbPinId 8) (portName "RD-") (portType INOUT))
        (port "9" (symbPinId 9) (portName "RX-") (portType INOUT))
        (port "10" (symbPinId 10) (portName "CRX") (portType INOUT))
        (port "11" (symbPinId 11) (portName "RX+") (portType INOUT))
        (port "12" (symbPinId 12) (portName "NC_3") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NC_4") (portType INOUT))
        (port "14" (symbPinId 14) (portName "TX-") (portType INOUT))
        (port "15" (symbPinId 15) (portName "CTX") (portType INOUT))
        (port "16" (symbPinId 16) (portName "TX+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "152")
    (property "Mouser_Part_Number" "710-7490100111")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/7490100111?qs=2sV1BwmkawTzYJbYKh1aHA%3D%3D")
    (property "Manufacturer_Name" "Wurth Elektronik")
    (property "Manufacturer_Part_Number" "7490100111")
    (property "Description" "Audio Transformers / Signal Transformers 10/100 Base-T SMT Transformer 1 Port")
    (property "Datasheet_Link" "https://www.we-online.com/katalog/datasheet/7490100111.pdf")
    (property "symbolName1" "7490100111")
)
