(part "NX3225GA_25MHZ_EXS00A-CG06750"
    (packageRef "NX3225GA25MHZEXS00ACG06750")
    (interface
        (port "1" (symbPinId 1) (portName "CRYSTAL_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CRYSTAL_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "NDK")
    (property "Manufacturer_Part_Number" "NX3225GA 25MHZ EXS00A-CG06750")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "CRYSTAL 25MHZ 8PF SMD")
    (property "Datasheet_Link" "https://www.ndk.com/images/products/catalog/c_NX3225GA-2_e.pdf")
    (property "symbolName1" "NX3225GA_25MHZ_EXS00A-CG06750")
)
