(part "IHLP6767DZER470M11"
    (packageRef "IHLP6767DZER470M11")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "IHLP6767DZER470M11")
    (property "Mouser_Part_Number" "70-IHLP6767DZER470M1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Dale/IHLP6767DZER470M11?qs=e2ByEPnK0IgJ3lh9QXlbaQ%3D%3D")
    (property "Arrow_Part_Number" "IHLP6767DZER470M11")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ihlp6767dzer470m11/vishay?utm_currency=USD&region=nac")
    (property "Description" "Fixed Inductors 47uH 20%")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/IHLP6767DZER470M11.pdf")
    (property "symbolName1" "IHLP6767DZER470M11")
)
